sudo: false
language: node_js
node_js:
  - 14
cache: npm
branches:
  only:
    - source
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: main
  on:
    branch: source
  local-dir: public
  