os: linux
dist: focal
language: node_js
node_js: lts/*
branches:
  only: source
script:
  - hexo generate
deploy:
  provider: pages
  strategy: git
  edge: true
  token: $GH_TOKEN
  target_branch: main
  on:
    branch: source
  local_dir: public
