name: Gitee Pages

on: page_build

jobs:
  build:
    environment: gitee-pages
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:alumik/alumik.github.io.git
          destination-repo: git@gitee.com:AlumiK/AlumiK.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: AlumiK
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: AlumiK/AlumiK
          branch: main
